version: '3'

volumes:
  database: {}
  uploads: {}
  redis: {}

services:
  database:
    image: postgres:11.6
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: permacoop
      PGUSER: docker
      PGPASSWORD: docker
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'

  api:
    image: node:14.3
    working_dir: '/var/www'
    depends_on:
      - database
    volumes:
      - './server:/var/www:cached'
      - 'uploads:/var/www/uploads'
    ports:
      - 8080:3000
    command: npm run start:dev

  client:
    image: node:14.3
    working_dir: '/var/www'
    depends_on:
      - api
    volumes:
      - './client:/var/www:cached'
    ports:
      - 8000:3000
      - 10000:10000
    command: npm run dev

  redis:
    image: 'redis:alpine'
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
      - 'redis:/var/lib/redis/data'
    restart: always
