version: '3'

volumes:
  database: {}

services:
  database:
    image: postgres:11.6
    environment:
      POSTGRES_USER: permacoop
      POSTGRES_PASSWORD: permacoop
      POSTGRES_DB: permacoop
      PGUSER: permacoop
      PGPASSWORD: permacoop
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'

  api:
    image: node:13.2
    working_dir: '/var/www'
    depends_on:
      - database
    volumes:
      - './server:/var/www:cached'
    ports:
      - 8080:3000
    command: npm run start:dev
